### ISSUE TITLE
Question about extracted proxy 3D shapes

### ISSUE THREAD

**Issue by tongxueqing** [microsoft/GRAM#1]
Thanks for your open-source work!  You mention "extract proxy 3D shapes of the generated object using the volume-based marching cubes algorithm". You use 24/48 surface manifold in total. I wonder how you decide which isosurface of 24/48 surface manifold  to reconstruct?

**Comment by YuDeng** [comment]
Hi, to get proxy 3D shapes, we do not use isosurfaces of our learned manifold. Instead, since our radiance generator is an MLP which can take arbitrary 3D location as input and output its color and alpha, we evenly sample N^3 points within a cube space and predict their alpha, and then use marching cubes with an empirical threshold to extract the 3D shape.
